prueba/directorio/urls.py
from django.conf.urls import url

from . import views
from django.contrib.auth import views as auth_views


app_name = 'directorio'

urlpatterns=[
	url(r'^user/$', views.Usuario, name='Usuario'),
	url(r'^user/register/$', views.User_Reg.as_view(), name='User_Reg'),
	#url(r'^user/login/$', views.User_Login.as_view(), name='User_Login'), 
	url(r'^user/login/$', views.User_Login, name='User_Login'),
	url(r'^user/logout/$', views.User_Logout, name='User_Logout'),
	url(r'^$', views.index, name='index'),
	url(r'^(?P<nombre_minion>\w+)/$', views.Web_Minion, name='Web_Minion'),
	url(r'^(?P<nombre_minion>\w+)/reinicio/$', views.Reboot_Minion, name='Reboot_Minion'),
	url(r'^(?P<nombre_minion>\w+)/comando/$', views.Send_Command, name='Send_Command'),
	url(r'^Reboot_All$', views.Reboot_All, name='Reboot_All'),
	url(r'^(?P<nombre_minion>\w+)/informacion$', views.Info_Minion, name='Info_Minion'),
	url(r'^(?P<nombre_minion>\w+)/informacion/servicio$', views.instalamosNginx, name='instalamosNginx'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG$', views.List_PKG_Minion, name='List_PKG_Minion'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/status$', views.applyStatus, name='applyStatus'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)$', views.Info_PKG_Minion, name='Info_PKG_Minion'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)/Ins$', views.PKG_Install, name='PKG_Install'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)/Remove$', views.PKG_Remove, name='PKG_Remove'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)$', views.Service_Start, name='Service_Start'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)$', views.Service_Stop, name='Service_Stop'),
	url(r'^(?P<nombre_minion>\w+)/infoPKG/resultado/(?P<nombre_PKG>[\w.:+-]+)$', views.Service_Restart, name='Service_Restart'),
]

prueba/prueba/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^directorio/', include('directorio.urls')),
]

prueba/directorio/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Minion(models.Model):
	nombre_texto = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __unicode__(self):
		return self.nombre_texto

prueba/directorio/forms.py
from django.contrib.auth.models import User
from django import forms


class TextoForm(forms.Form):
   comandoText = forms.CharField(label='comandoText', max_length=100)
class InfoForm(forms.Form):
   infoText = forms.CharField(label='infoText', max_length=100)

class UserForm_Reg(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'email', 'password']

class UserForm_Login(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password']

prueba/directorio/views.py
from django.shortcuts import get_object_or_404, render, render_to_response, redirect
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.template import loader
from django.views import generic
from .models import Minion
from .forms import TextoForm, InfoForm, UserForm_Reg, UserForm_Login


from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
#from django import forms

import salt.client
import salt.config
import salt.loader

name_User=""

# Create your views here.
@login_required(login_url='user/')
def index(request):
	local = salt.client.LocalClient()
	listaMinions=local.cmd('*', 'test.ping', '')
	    
	context = {'listaMinions':listaMinions, 'name_User':name_User}    	
	return render(request, 'index.html', context)

#recibimos el nombre clicado en indice y le llevamos a la pagina general del minionX
@login_required(login_url='user/')
def Web_Minion(request, nombre_minion):
	local = salt.client.LocalClient()
	comando=local.cmd(nombre_minion, 'cmd.run', ['uname -n'])
	context = {'nombre_minion':nombre_minion, 'comando':comando}
	return render(request, 'Web_Minion.html', context)

#reiniciamos el minion, venimos de pag info del minionX
@login_required(login_url='user/')
def Reboot_Minion(request, nombre_minion):
	local = salt.client.LocalClient()
	#comando=local.cmd(nombre_minion, 'cmd.run', ['df -h /home'])
	comando=local.cmd(nombre_minion, 'cmd.run', ['reboot'])
	context = {'nombre_minion':nombre_minion, 'comando':comando}
	return render(request, 'Reboot_Minion.html', context)

#nos llega el comando introducido, lo mandamos por argumentos y le llevamos a la Info_Command
@login_required(login_url='user/')
def Send_Command(request, nombre_minion):
    if request.method == 'POST':
        form = TextoForm(request.POST)
        if form.is_valid():     
			comando_introducido=form.cleaned_data['comandoText']
			local = salt.client.LocalClient()
			resultado_comando=local.cmd(nombre_minion, 'cmd.run', [comando_introducido])
			context = {'nombre_minion':nombre_minion, 'comando_introducido':comando_introducido, 'resultado_comando':resultado_comando}
			return render(request, 'Info_Command.html', context)

    else:
        form = TextoForm()
	context = {'nombre_minion':nombre_minion, 'form':form}
	return render(request, 'Send_Command.html', context)



#reinicio de todas las maquinas, en el indice
@login_required(login_url='user/')
def Reboot_All(request):
	local = salt.client.LocalClient()
	maquinas=local.cmd('*', 'test.ping', '')
	comando=local.cmd('*', 'cmd.run', ['reboot'])
	context = {'comando':comando, 'maquinas':maquinas}
	return render(request, 'Reboot_All.html', context)

@login_required(login_url='user/')
def Info_Minion(request, nombre_minion):
	local = salt.client.LocalClient()
	memoria_info=local.cmd(nombre_minion, 'disk.usage', [''])
	ip_info = local.cmd(nombre_minion, 'network.ip_addrs', '')
	fecha_info = local.cmd(nombre_minion, 'cmd.run', ['date'])
	#paquetes_info = local.cmd(nombre_minion, 'pkg.list_pkgs', '')
	#info_nginx = local.cmd(nombre_minion, 'service.status', ['nginx'])
	context = {'nombre_minion':nombre_minion, 'ip_info':ip_info,'fecha_info':fecha_info, 'memoria_info':memoria_info}
	return render(request, 'Info_Minion.html', context)

@login_required(login_url='user/')
def instalamosNginx(request, nombre_minion):
	local = salt.client.LocalClient()
	local.cmd(nombre_minion, 'state.apply', ['bin.nginx'])
	info_nginx = local.cmd(nombre_minion, 'service.status', ['nginx'])
	context = {'nombre_minion':nombre_minion, 'info_nginx':info_nginx}
	return render(request, 'detalle8.html', context)

@login_required(login_url='user/')
def applyStatus(request, nombre_minion):
	local = salt.client.LocalClient()
	info_estado=local.cmd(nombre_minion, 'state.apply', ['bin.nginx'])
	context={'nombre_minion':nombre_minion, 'info_estado':info_estado}
	return render(request, 'applyStatus.html', context)

#informacion del paquete
@login_required(login_url='user/')
def List_PKG_Minion(request, nombre_minion):
    if request.method == 'POST':
        form = InfoForm(request.POST)
        if form.is_valid():     
		nombre_PKG=form.cleaned_data['infoText']
		print nombre_PKG
		return HttpResponseRedirect(reverse('directorio:Info_PKG_Minion', args=(nombre_minion, nombre_PKG,)))

    else:
    	local = salt.client.LocalClient()
    	paquetes_info = local.cmd(nombre_minion, 'pkg.list_pkgs', '')
        form = InfoForm()

	context = {'nombre_minion':nombre_minion, 'form':form, 'paquetes_info':paquetes_info }
	return render(request, 'List_PKG_Minion.html', context)

#ejecutamos para ver la info del paquete
@login_required(login_url='user/')
def Info_PKG_Minion(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	version_PKG = local.cmd(nombre_minion, 'pkg.version', [nombre_PKG])
	info_estado = local.cmd(nombre_minion, 'service.status', [nombre_PKG])
	context={'nombre_minion':nombre_minion,'nombre_PKG':nombre_PKG, 'info_estado':info_estado, 'info_PKG':info_PKG, 'version_PKG':version_PKG}
	return render(request, 'Info_PKG_Minion.html', context)

@login_required(login_url='user/')
def PKG_Install(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info=local.cmd(nombre_minion, 'pkg.install', [nombre_PKG])
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	context={'nombre_minion':nombre_minion, 'nombre_PKG':nombre_PKG,'info':info,  'info_PKG':info_PKG}
	return render(request, 'InstallPKG.html', context)

@login_required(login_url='user/')
def PKG_Remove(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info=local.cmd(nombre_minion, 'pkg.remove', [nombre_PKG])
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	context={'nombre_minion':nombre_minion, 'nombre_PKG':nombre_PKG,'info':info, 'info_PKG':info_PKG}
	return render(request, 'RemovePKG.html', context)

def Service_Start(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	version_PKG = local.cmd(nombre_minion, 'pkg.version', [nombre_PKG])
	info_estado = local.cmd(nombre_minion, 'service.start', [nombre_PKG])
	context={'nombre_minion':nombre_minion,'nombre_PKG':nombre_PKG, 'info_estado':info_estado, 'info_PKG':info_PKG, 'version_PKG':version_PKG}
	return render(request, 'Info_PKG_Minion.html', context)

def Service_Stop(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	version_PKG = local.cmd(nombre_minion, 'pkg.version', [nombre_PKG])
	info_estado = local.cmd(nombre_minion, 'service.stop', [nombre_PKG])
	context={'nombre_minion':nombre_minion,'nombre_PKG':nombre_PKG, 'info_estado':info_estado, 'info_PKG':info_PKG, 'version_PKG':version_PKG}
	return render(request, 'Info_PKG_Minion.html', context)

def Service_Restart(request,nombre_minion, nombre_PKG):
	local = salt.client.LocalClient()
	info_PKG = local.cmd(nombre_minion, 'pkg.info_installed', [nombre_PKG])
	version_PKG = local.cmd(nombre_minion, 'pkg.version', [nombre_PKG])
	info_estado = local.cmd(nombre_minion, 'service.restart', [nombre_PKG])
	context={'nombre_minion':nombre_minion,'nombre_PKG':nombre_PKG, 'info_estado':info_estado, 'info_PKG':info_PKG, 'version_PKG':version_PKG}
	return render(request, 'Info_PKG_Minion.html', context)

#------------------USUARIOS---------------------------#

def Usuario(request):
	return render(request, 'Usuario.html')


class User_Reg(View):
	form_class = UserForm_Reg

	def get(self, request):
		form = self.form_class(None)
		return render(request, 'registrar.html',{'form':form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():

			user = form.save(commit=False)
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user.set_password(password)
			user.save()
			
			user = authenticate(username=username, password=password)

			if user is not None:
				if user.is_active:
					login(request, user)
					return redirect('directorio:index')

		return render(request, 'registrar.html',{'form':form})




def User_Logout(request):
    logout(request)
    return redirect('directorio:index')




#https://docs.djangoproject.com/en/1.10/topics/auth/default/
def User_Login(request):
    	if request.method == 'POST':
    		print "entro"
        	form = UserForm_Login(request.POST)
        	if form.is_valid():    
				username = form.cleaned_data['username']
				password = form.cleaned_data['password']
				print "continuo" 
				user = authenticate(username=username, password=password)
				if user is not None:
					login(request, user)
					return redirect('directorio:index')

    	else:
        	form = UserForm_Login()


    	context = {'form':form}
	return render(request, 'login.html', context)


#class User_Login(View):
#	form_class = UserForm_Login
#
#	def get(self, request):
#		form = self.form_class(None)
#		return render(request, 'login.html',{'form':form})
#
#	def post(self, request):
#		form = self.form_class(request.POST)
#		if form.is_valid():
#			username = form.cleaned_data['username']
#			password = form.cleaned_data['password']
#			print username, password
#			user = authenticate(username=username, password=password)
#			print user
#			if user is not None:
#					print "entro"
#					login(request, user)
#					return redirect('directorio:index')
#
#		return render(request, 'login.html',{'form':form})




#def registrar_usuario(request):
#	if request.method=='POST':
#		formulario = UserCreationForm(request.POST)
#		if formulario.is_valid:
#			formulario.save()
#			return HttpResponseRedirect('/')
#		else:

prueba/directorio/templates/Info_Minion.html
<!DOCTYPE html>
<html lang="es">
<head>

	{% load staticfiles %}

	<meta charset="utf-8">
	<title>Info Device</title>

	<link href="{% static 'configuracion/estilo.css' %}" rel="stylesheet">

</head>
 
<body>
	
	<header id="main-header">
		<div>
			<img src="{% static 'configuracion/images/HP_Logo.png' %}">
		</div>
		
		<a id="logo-header" href="{% url 'directorio:index' %}">
			<span class="site-name">DCW</span>
			<span class="site-desc">Device Control Web</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li>{{name_User}}</li>
				<li><a href="{% url 'directorio:User_Logout' %}">Logout</a></li>
			</ul>
		</nav><!-- / nav -->
 
	</header><!-- / #main-header -->
 
	<div id ="main-menu">
		<ul>
		<li><a href="{% url 'directorio:Info_Minion' nombre_minion %}">Informacion</a></li>
		<li><a href="{% url 'directorio:List_PKG_Minion' nombre_minion %}">Paquetes</a></li>
		<li><a href="{% url 'directorio:Send_Command' nombre_minion %}">Comando</a></li>
		<li><a href="{% url 'directorio:Reboot_Minion' nombre_minion %}">Reiniciar</a></li>
		</ul>
		
	</div >
	<div id="main-content">
		<section id="main-content">
		<h1><a href="{% url 'directorio:Web_Minion' nombre_minion %}">{{nombre_minion}}</a></h1>

		<div class="content">
			<h2>Informacion</h2>
			<p>Fecha:</p>
			{% for key,value in fecha_info.items %}
				<li class="fecha"> 		{{value}} </li>
			{% endfor %}
			<p>IPs:</p>
			
			{% for key,value in ip_info.items %}
				{% for i in value %}
					<li>{{i}} </li>
				{% endfor %}
			{% endfor %}

			<p>Memoria</p>
			{% for key,value in memoria_info.items %}
				{% for key1, value1 in value.items %}
					<li>{{key1}}:</li>
					{% for key2, value2 in value1.items %}
					<ul>
						<p>{{key2}}:  {{value2}}</p>
					</ul>
					{% endfor %}
				{% endfor %}
			{% endfor %}	

		</div>

	
	</section> <!-- / #main-content -->
 
	
	</div>

	<div>
	<footer id="main-footer">
		<p>&copy; 2016 Francisco Javier Pereña Martin</p>
	</footer> <!-- / #main-footer -->

	</div>

 
	
</body>
</html>

prueba/directorio/templates/RemovePKG.html
<!DOCTYPE html>
<html lang="es">
<head>

	{% load staticfiles %}

	<meta charset="utf-8">
	<title>Info PKG Device</title>

	<link href="{% static 'configuracion/estilo.css' %}" rel="stylesheet">

</head>
 
<body>
	
	<header id="main-header">
		<div>
			<img src="{% static 'configuracion/images/HP_Logo.png' %}">
		</div>
		
		<a id="logo-header" href="{% url 'directorio:index' %}">
			<span class="site-name">DCW</span>
			<span class="site-desc">Device Control Web</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li>{{name_User}}</li>
				<li><a href="{% url 'directorio:User_Logout' %}">Logout</a></li>
			</ul>
		</nav><!-- / nav -->
 
	</header><!-- / #main-header -->
 
	<div id ="main-menu">
		<ul>
		<li><a href="{% url 'directorio:Info_Minion' nombre_minion %}">Informacion</a></li>
		<li><a href="{% url 'directorio:List_PKG_Minion' nombre_minion %}">Paquetes</a></li>
		<li><a href="{% url 'directorio:Send_Command' nombre_minion %}">Comando</a></li>
		<li><a href="{% url 'directorio:Reboot_Minion' nombre_minion %}">Reiniciar</a></li>
		</ul>
		
	</div >
	<div id="main-content">
		<section id="main-content">
		<h1><a href="{% url 'directorio:Web_Minion' nombre_minion %}">{{nombre_minion}}</a></h1>

		<div class="content">
			<h2>Desinstalación del paquete: {{nombre_PKG}}</h2>
			
			<p>{{info}}</p>
		</div>

	
	</section> <!-- / #main-content -->
 
	
	</div>

	<div>
	<footer id="main-footer">
		<p>&copy; 2016 Francisco Javier Pereña Martin</p>
	</footer> <!-- / #main-footer -->

	</div>

 
	
</body>
</html>

prueba/directorio/templates/Send_Command.html
<!DOCTYPE html>
<html lang="es">
<head>

	{% load staticfiles %}

	<meta charset="utf-8">
	<title>Command Device</title>

	<link href="{% static 'configuracion/estilo.css' %}" rel="stylesheet">

</head>
 
<body>
	
	<header id="main-header">
		<div>
			<img src="{% static 'configuracion/images/HP_Logo.png' %}">
		</div>
		
		<a id="logo-header" href="{% url 'directorio:index' %}">
			<span class="site-name">DCW</span>
			<span class="site-desc">Device Control Web</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li>{{name_User}}</li>
				<li><a href="{% url 'directorio:User_Logout' %}">Logout</a></li>
			</ul>
		</nav><!-- / nav -->
 
	</header><!-- / #main-header -->
 
	<div id ="main-menu">
		<ul>
		<li><a href="{% url 'directorio:Info_Minion' nombre_minion %}">Informacion</a></li>
		<li><a href="{% url 'directorio:List_PKG_Minion' nombre_minion %}">Paquetes</a></li>
		<li><a href="{% url 'directorio:Send_Command' nombre_minion %}">Comando</a></li>
		<li><a href="{% url 'directorio:Reboot_Minion' nombre_minion %}">Reiniciar</a></li>
		</ul>
		
	</div >
	<div id="main-content">
		<section id="main-content">
		<h1><a href="{% url 'directorio:Web_Minion' nombre_minion %}">{{nombre_minion}}</a></h1>

		<div class="content">
			
			<h2>Enviamos comando</h2>

			<p>Introduzca el comando a enviar</p>
			<form action="" method="post">
			    {% csrf_token %}
			    {{ form }}
			    <input  id="textoEntrada" name="textoEntrada" type="submit" value="Submit" />
			</form>


		</div>

	
	</section> <!-- / #main-content -->
 
	
	</div>

	<div>
	<footer id="main-footer">
		<p>&copy; 2016 Francisco Javier Pereña Martin</p>
	</footer> <!-- / #main-footer -->

	</div>

 
	
</body>
</html>

prueba/directorio/templates/Web_Minion.html
<!DOCTYPE html>
<html lang="es">
<head>

	{% load staticfiles %}

	<meta charset="utf-8">
	<title>Web Device</title>

	<link href="{% static 'configuracion/estilo.css' %}" rel="stylesheet">

</head>
 
<body>
	
	<header id="main-header">
		<div>
			<img src="{% static 'configuracion/images/HP_Logo.png' %}">
		</div>
		
		<a id="logo-header" href="{% url 'directorio:index' %}">
			<span class="site-name">DCW</span>
			<span class="site-desc">Device Control Web</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li>{{name_User}}</li>
				<li><a href="{% url 'directorio:User_Logout' %}">Logout</a></li>
			</ul>
		</nav><!-- / nav -->
 
	</header><!-- / #main-header -->
 
	<div id ="main-menu">
		<ul>
		<li><a href="{% url 'directorio:Info_Minion' nombre_minion %}">Informacion</a></li>
		<li><a href="{% url 'directorio:List_PKG_Minion' nombre_minion %}">Paquetes</a></li>
		<li><a href="{% url 'directorio:Send_Command' nombre_minion %}">Comando</a></li>
		<li><a href="{% url 'directorio:Reboot_Minion' nombre_minion %}">Reiniciar</a></li>
		</ul>
		
	</div >
	<div id="main-content">
		<section id="main-content">
		<h1>{{nombre_minion}}</h1>

		<div class="content">
			<h2>Pagina personal de {{nombre_minion}}</h2>
			<p>Desde aqui podrá gestionar la maquina y recibir información sobre esta</p>
			<ul>
				<li>- Informacion: Conocer información acerca de la maquina</li>
				<li>- Paquetes: Informacion de los paquetes instalados, asi como instalar o eliminar(Estado)</li>
				<li>- Comando: Enviar comandos a la máquina para conocer informacion en concreto</li>
				<li>- Reiniciar: Se reiniciará esta maquina por completo</li>
			</ul>


		</div>

	
	</section> <!-- / #main-content -->
 
	
	</div>

	<div>
	<footer id="main-footer">
		<p>&copy; 2016 Francisco Javier Pereña Martin</p>
	</footer> <!-- / #main-footer -->

	</div>

 
	
</body>
</html>

prueba/directorio/templates/applyStatus.html
<!DOCTYPE html>
<html lang="es">
<head>

	{% load staticfiles %}

	<meta charset="utf-8">
	<title>PKG_Status Device</title>

	<link href="{% static 'configuracion/estilo.css' %}" rel="stylesheet">

</head>
 
<body>
	
	<header id="main-header">
		<div>
			<img src="{% static 'configuracion/images/HP_Logo.png' %}">
		</div>
		
		<a id="logo-header" href="{% url 'directorio:index' %}">
			<span class="site-name">DCW</span>
			<span class="site-desc">Device Control Web</span>
		</a> <!-- / #logo-header -->

		<nav>
			<ul>
				<li>{{name_User}}</li>
				<li><a href="{% url 'directorio:User_Logout' %}">Logout</a></li>
			</ul>
		</nav><!-- / nav -->
 
	</header><!-- / #main-header -->
 <div id ="main-menu">
		<ul>
		<li><a href="{% url 'directorio:Info_Minion' nombre_minion %}">Informacion</a></li>
		<li><a href="{% url 'directorio:List_PKG_Minion' nombre_minion %}">Paquetes</a></li>
		<li><a href="{% url 'directorio:Send_Command' nombre_minion %}">Comando</a></li>
		<li><a href="{% url 'directorio:Reboot_Minion' nombre_minion %}">Reiniciar</a></li>
		</ul>
		
	</div >
	<div id="main-content">
		<section id="main-content">
		<h1>{{nombre_minion}}</h1>

		<div class="content">
			<h2>Aplicamos el estado</h2>
			<p>{{info_estado}}</p>

		</div>

	
	</section> <!-- / #main-content -->
 
	
	</div>

	<div>
	<footer id="main-footer">
		<p>&copy; 2016 Francisco Javier Pereña Martin</p>
	</footer> <!-- / #main-footer -->

	</div>

 
	
</body>
</html>

prueba/directorio/templates/detalle11_Desin.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Detalles</title>
	</head>
	<body> 
		<h1>Desinstalacion en {{nombre_minion}}</h1>
		<h2>Paquete: {{nombre_PKG}}</h2>

		<p>Espere unos segundos...</p>
		<p>Info PKG {{info_PKG}}</p>
		<a href="{% url 'directorio:detalle10' nombre_minion nombre_PKG %}">Volver a Info_Paquete</a>

		<a href="{% url 'directorio:index' %}">Indice</a>
	</body>
</html>

prueba/directorio/templates/detalle11_Ins.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Detalles</title>
	</head>
	<body> 
		<h1>Instalacion en {{nombre_minion}}</h1>
		<h2>Paquete: {{nombre_PKG}}</h2>

		<p>Espere unos segundos...</p>
		<p>Info PKG {{info_PKG}}</p>
		<a href="{% url 'directorio:detalle10' nombre_minion nombre_PKG %}">Volver a Info_Paquete</a>

		<a href="{% url 'directorio:index' %}">Indice</a>
	</body>
</html>

prueba/directorio/templates/detalle3.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Detalles</title>
	</head>
	<body> 
		<h1>Detalle3</h1>
		<h2>Reiniciando....</h2>
		<p>Le mandamos Comando a {{nombre_minion}}</p>
		<p>Resultado: {{comando}}</p>
		<a href="{% url 'directorio:index' %}">Indice</a>

		
	</body>
</html>

prueba/directorio/templates/detalle7.html
<html>
	<head>
		{% load staticfiles %}

		<link rel="stylesheet" type="text/css" href="{% static 'configuracion/style.css' %}" />
		<title>Detalles</title>
	</head>
	<body> 
		<h1>Detalle7</h1>
		<h3>Informacion de {{nombre_minion}}</h3>
		<p>Con fecha {{fecha_info}}</p>

		<p>La IP es: {{ip_info}}</p>

		<a href="{% url 'directorio:instalamosNginx' nombre_minion %}">Aplicamos estado(instalar Nginx, modulo personalizado)</a>
		<a href="{% url 'directorio:detalle9' nombre_minion %}">Informacion PKG</a>
		<a href="{% url 'directorio:index' %}">Indice</a>

		
	</body>
</html>